apiVersion: apps/v1
kind: Deployment
metadata:
  name: codecheck-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codecheck
  template:
    metadata:
      labels:
        app: codecheck
    spec:
      containers:
        - name: codecheck
          image: codecheck-app
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 400
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 300
            periodSeconds: 300
            httpGet:
              path: /health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: codecheck-app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: codecheck
  ports:
    - port: 80
      targetPort: 8080